name: Build and Push Changed Services to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth_service, stock_kr_service, exchange_service, portfolio_service]

    env:
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: 707677861059.dkr.ecr.ap-northeast-2.amazonaws.com
      IMAGE_TAG: latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check changes and build/push service if needed
        run: |
          PREV_COMMIT=$(git rev-parse HEAD~1)
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -qE "^${{ matrix.service }}/|^config\.py|^db\.py|^\.env"; then
            echo "Preparing ${{ matrix.service }}..."
            cp config.py ${{ matrix.service }}/
            cp db.py ${{ matrix.service }}/
            cp .env ${{ matrix.service }}/
            if [ "${{ matrix.service }}" == "stock_kr_service" ]; then
              # koreainvestment.key is already in stock_kr_service directory
              echo "koreainvestment.key is already in stock_kr_service directory"
            fi
            echo "Building and pushing ${{ matrix.service }}..."
            docker build -t $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG ./${{ matrix.service }}
            docker push $ECR_REGISTRY/${{ matrix.service }}:$IMAGE_TAG
            echo "Pushed ${{ matrix.service }} to ECR successfully."
            # Clean up
            rm ${{ matrix.service }}/config.py ${{ matrix.service }}/db.py ${{ matrix.service }}/.env
          else
            echo "No changes detected for ${{ matrix.service }}."
          fi
