name: Initial Build and Push All Services to ECR

on:
  workflow_dispatch:  # 수동 실행 가능하도록 설정

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      ECR_REGISTRY: 707677861059.dkr.ecr.ap-northeast-2.amazonaws.com
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Auth Service Image
        run: |
          docker build -t $ECR_REGISTRY/auth_service:$IMAGE_TAG ./auth_service
          docker push $ECR_REGISTRY/auth_service:$IMAGE_TAG

      - name: Build and Push Stock KR Service Image
        run: |
          docker build -t $ECR_REGISTRY/stock_kr_service:$IMAGE_TAG ./stock_kr_service
          docker push $ECR_REGISTRY/stock_kr_service:$IMAGE_TAG

      - name: Build and Push Exchange Service Image
        run: |
          docker build -t $ECR_REGISTRY/exchange_service:$IMAGE_TAG ./exchange_service
          docker push $ECR_REGISTRY/exchange_service:$IMAGE_TAG

      - name: Build and Push Portfolio Service Image
        run: |
          docker build -t $ECR_REGISTRY/portfolio_service:$IMAGE_TAG ./portfolio_service
          docker push $ECR_REGISTRY/portfolio_service:$IMAGE_TAG
